"""
test_bulk_import.py

Real pytest coverage for import_sdf(), using genuinely valid SDF files
generated by RDKit itself (not hand-typed, to avoid syntax errors) with
realistic PubChem-format property tags - representative sample data,
not an actual downloaded bulk file, since this sandbox cannot reach
pubchem.ncbi.nlm.nih.gov (confirmed directly - see database_lookup.py
and this module's own docstring).
"""

import os
import tempfile
import pytest
from rdkit import Chem
from ambigchem.local_database import create_database, lookup, count_records
from ambigchem.bulk_import import import_sdf


@pytest.fixture
def sample_sdf_and_db():
    with tempfile.TemporaryDirectory() as tmpdir:
        sdf_path = os.path.join(tmpdir, "sample.sdf")
        db_path = os.path.join(tmpdir, "compounds.db")
        create_database(db_path)

        writer = Chem.SDWriter(sdf_path)

        mol1 = Chem.MolFromSmiles("CC(=O)OC1=CC=CC=C1C(=O)O")  # aspirin
        mol1.SetProp("_Name", "aspirin")
        mol1.SetProp("PUBCHEM_IUPAC_NAME", "2-acetyloxybenzoic acid")
        mol1.SetProp("PUBCHEM_MOLECULAR_FORMULA", "C9H8O4")
        mol1.SetProp("PUBCHEM_IUPAC_TRADITIONAL_NAME", "aspirin")
        writer.write(mol1)

        mol2 = Chem.MolFromSmiles("CN1C=NC2=C1C(=O)N(C(=O)N2C)C")  # caffeine
        mol2.SetProp("_Name", "caffeine")
        mol2.SetProp("PUBCHEM_IUPAC_NAME", "1,3,7-trimethylpurine-2,6-dione")
        mol2.SetProp("PUBCHEM_MOLECULAR_FORMULA", "C8H10N4O2")
        writer.write(mol2)
        writer.close()

        yield sdf_path, db_path


@pytest.fixture
def real_world_sample_with_synonym_gap():
    """Mirrors the REAL, live-confirmed gap: a genuine PubChem SDF entry
    (CID 2244, aspirin) whose SDF tags contain NO 'aspirin' anywhere -
    only formal name types - confirmed by directly inspecting a real
    downloaded PubChem bulk file before writing this test. The synonym
    file is where 'aspirin' the trade name actually lives."""
    with tempfile.TemporaryDirectory() as tmpdir:
        sdf_path = os.path.join(tmpdir, "sample.sdf")
        syn_path = os.path.join(tmpdir, "synonyms.tsv")
        db_path = os.path.join(tmpdir, "compounds.db")
        create_database(db_path)

        mol = Chem.MolFromSmiles("CC(=O)OC1=CC=CC=C1C(=O)O")
        mol.SetProp("PUBCHEM_COMPOUND_CID", "2244")
        mol.SetProp("PUBCHEM_MOLECULAR_FORMULA", "C9H8O4")
        mol.SetProp("PUBCHEM_IUPAC_TRADITIONAL_NAME", "acetylsalicylic acid")  # NOT "aspirin"
        writer = Chem.SDWriter(sdf_path)
        writer.write(mol)
        writer.close()

        with open(syn_path, "w") as f:
            f.write("2244\taspirin\n")
            f.write("2244\tBayer Aspirin\n")

        yield sdf_path, syn_path, db_path


def test_import_populates_database(sample_sdf_and_db):
    sdf_path, db_path = sample_sdf_and_db
    imported = import_sdf(sdf_path, db_path, source="pubchem")
    assert imported > 0
    assert count_records(db_path) > 0


def test_multiple_names_per_molecule_all_lookupable(sample_sdf_and_db):
    """Aspirin has both a trivial name and an IUPAC name in the sample -
    both should be independently importable and lookupable, the real
    'multiple names, same formula' case."""
    sdf_path, db_path = sample_sdf_and_db
    import_sdf(sdf_path, db_path, source="pubchem")

    assert lookup(db_path, "aspirin").formula == "C9H8O4"
    assert lookup(db_path, "2-acetyloxybenzoic acid").formula == "C9H8O4"


def test_second_molecule_also_imported_correctly(sample_sdf_and_db):
    sdf_path, db_path = sample_sdf_and_db
    import_sdf(sdf_path, db_path, source="pubchem")

    assert lookup(db_path, "caffeine").formula == "C8H10N4O2"


def test_offline_lookup_after_import_needs_zero_network(sample_sdf_and_db):
    """The actual point of this whole module: once imported, lookups
    are pure local SQLite queries - no network call anywhere in this
    path, confirmed by the fact this test runs correctly in a sandbox
    with confirmed-restricted network access."""
    sdf_path, db_path = sample_sdf_and_db
    import_sdf(sdf_path, db_path, source="pubchem")

    result = lookup(db_path, "aspirin")
    assert result is not None
    assert result.source == "pubchem"


def test_synonym_file_closes_the_real_confirmed_gap(real_world_sample_with_synonym_gap):
    """The real, live-confirmed problem this test protects against:
    'aspirin' the trade name is genuinely absent from PubChem's own
    Compound SDF tags (confirmed by inspecting a real downloaded file -
    CID 2244 had no 'aspirin' anywhere, only 'acetylsalicylic acid').
    Without the synonym file, this lookup would incorrectly return None."""
    sdf_path, syn_path, db_path = real_world_sample_with_synonym_gap

    import_sdf(sdf_path, db_path, source="pubchem", synonym_path=syn_path)

    assert lookup(db_path, "aspirin") is not None
    assert lookup(db_path, "aspirin").formula == "C9H8O4"
    assert lookup(db_path, "bayer aspirin") is not None
    assert lookup(db_path, "acetylsalicylic acid") is not None


def test_without_synonym_file_the_real_gap_still_exists(real_world_sample_with_synonym_gap):
    """Confirms the gap is real, not hypothetical: the SAME sample data,
    imported WITHOUT the synonym file, genuinely fails to find 'aspirin'
    - exactly reproducing what was actually observed on a real machine."""
    sdf_path, syn_path, db_path = real_world_sample_with_synonym_gap

    import_sdf(sdf_path, db_path, source="pubchem")  # no synonym_path

    assert lookup(db_path, "aspirin") is None
    assert lookup(db_path, "acetylsalicylic acid") is not None  # still findable, it's a real SDF tag


def test_synonym_filtering_excludes_irrelevant_cids(real_world_sample_with_synonym_gap):
    """Direct proof of the real fix for the MemoryError found on a live
    run: a synonym file containing an entry for a CID NOT present in the
    SDF (simulating PubChem's full, global file containing far more CIDs
    than any one SDF slice) must be correctly filtered out, not loaded."""
    sdf_path, syn_path, db_path = real_world_sample_with_synonym_gap

    # Add a synonym line for a CID that does NOT exist in our SDF sample
    with open(syn_path, "a") as f:
        f.write("999999999\tirrelevant compound name\n")

    from ambigchem.bulk_import import load_synonym_map
    filtered_map = load_synonym_map(syn_path, relevant_cids={"2244"})

    assert "2244" in filtered_map
    assert "999999999" not in filtered_map, "Irrelevant CID must be filtered out, not loaded into memory"
